<?php

namespace Database\Seeders\Bread;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemsSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('menu_items')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('menu_items')->insert(array (
  'id' => 1,
  'menu_id' => 1,
  'title' => 'Dashboard',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-boat',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 1,
  'created_at' => '2024-09-26 03:11:15',
  'updated_at' => '2025-03-05 22:14:14',
  'route' => 'voyager.dashboard',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 4,
  'menu_id' => 1,
  'title' => 'Roles',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-lock',
  'color' => NULL,
  'parent_id' => 16,
  'order' => 1,
  'created_at' => '2024-09-26 03:11:16',
  'updated_at' => '2025-03-15 23:10:47',
  'route' => 'voyager.roles.index',
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 5,
  'menu_id' => 1,
  'title' => 'Tools',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-tools',
  'color' => NULL,
  'parent_id' => NULL,
  'order' => 13,
  'created_at' => '2024-09-26 03:11:16',
  'updated_at' => '2025-04-08 10:01:21',
  'route' => NULL,
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 6,
  'menu_id' => 1,
  'title' => 'Menu Builder',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-list',
  'color' => NULL,
  'parent_id' => 5,
  'order' => 4,
  'created_at' => '2024-09-26 03:11:16',
  'updated_at' => '2025-04-08 10:01:21',
  'route' => 'voyager.menus.index',
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 7,
  'menu_id' => 1,
  'title' => 'Database',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-data',
  'color' => NULL,
  'parent_id' => 5,
  'order' => 5,
  'created_at' => '2024-09-26 03:11:16',
  'updated_at' => '2025-04-08 10:01:21',
  'route' => 'voyager.database.index',
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 8,
  'menu_id' => 1,
  'title' => 'Compass',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-compass',
  'color' => NULL,
  'parent_id' => 5,
  'order' => 6,
  'created_at' => '2024-09-26 03:11:16',
  'updated_at' => '2025-04-08 10:01:21',
  'route' => 'voyager.compass.index',
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 9,
  'menu_id' => 1,
  'title' => 'BREAD',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-bread',
  'color' => '#000000',
  'parent_id' => 5,
  'order' => 7,
  'created_at' => '2024-09-26 03:11:16',
  'updated_at' => '2025-08-15 11:06:37',
  'route' => 'voyager.bread.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 10,
  'menu_id' => 1,
  'title' => 'Settings',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-settings',
  'color' => NULL,
  'parent_id' => 5,
  'order' => 2,
  'created_at' => '2024-09-26 03:11:16',
  'updated_at' => '2025-03-05 21:31:46',
  'route' => 'voyager.settings.index',
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 14,
  'menu_id' => 1,
  'title' => 'Agent',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-list',
  'color' => '#000000',
  'parent_id' => 17,
  'order' => 2,
  'created_at' => '2024-09-26 04:34:58',
  'updated_at' => '2024-12-10 10:00:55',
  'route' => 'voyager.agent.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 15,
  'menu_id' => 1,
  'title' => 'Clients',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-list',
  'color' => '#000000',
  'parent_id' => 17,
  'order' => 1,
  'created_at' => '2024-09-26 04:37:20',
  'updated_at' => '2024-12-10 10:00:55',
  'route' => 'voyager.client.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 16,
  'menu_id' => 1,
  'title' => 'Admin',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-person',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 12,
  'created_at' => '2024-09-26 06:11:58',
  'updated_at' => '2025-04-08 10:01:21',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 17,
  'menu_id' => 1,
  'title' => 'User Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-group',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 2,
  'created_at' => '2024-09-26 06:14:02',
  'updated_at' => '2024-12-03 09:54:25',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 18,
  'menu_id' => 1,
  'title' => 'Agency Profile',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-company',
  'color' => '#000000',
  'parent_id' => 31,
  'order' => 1,
  'created_at' => '2024-09-30 08:01:10',
  'updated_at' => '2024-12-17 17:28:43',
  'route' => 'voyager.agency.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 19,
  'menu_id' => 1,
  'title' => 'Product Types',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-categories',
  'color' => '#000000',
  'parent_id' => 27,
  'order' => 1,
  'created_at' => '2024-09-30 08:12:49',
  'updated_at' => '2024-12-27 16:14:19',
  'route' => 'voyager.product-type.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 20,
  'menu_id' => 1,
  'title' => 'Product List',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-window-list',
  'color' => '#000000',
  'parent_id' => 27,
  'order' => 2,
  'created_at' => '2024-09-30 08:26:47',
  'updated_at' => '2024-12-27 16:14:19',
  'route' => 'voyager.product.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 21,
  'menu_id' => 1,
  'title' => 'Document Types',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-categories',
  'color' => '#000000',
  'parent_id' => 47,
  'order' => 1,
  'created_at' => '2024-09-30 08:39:39',
  'updated_at' => '2024-12-27 16:13:22',
  'route' => 'voyager.document-type.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 22,
  'menu_id' => 1,
  'title' => 'Product Agreements',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-paper-plane',
  'color' => '#000000',
  'parent_id' => 47,
  'order' => 2,
  'created_at' => '2024-09-30 08:51:50',
  'updated_at' => '2024-12-27 16:13:22',
  'route' => 'voyager.product-agreement.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 24,
  'menu_id' => 1,
  'title' => 'Bank Status',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-upload',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 11,
  'created_at' => '2024-09-30 09:44:31',
  'updated_at' => '2025-04-08 10:01:12',
  'route' => 'voyager.bank-file-upload.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 27,
  'menu_id' => 1,
  'title' => 'Product',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-bag',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 5,
  'created_at' => '2024-10-11 18:02:57',
  'updated_at' => '2025-03-18 16:15:18',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 28,
  'menu_id' => 1,
  'title' => 'Product Orders',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-archive',
  'color' => '#000000',
  'parent_id' => 27,
  'order' => 3,
  'created_at' => '2024-10-11 18:12:37',
  'updated_at' => '2024-12-27 16:14:19',
  'route' => 'voyager.product-order.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 29,
  'menu_id' => 1,
  'title' => 'Corporate',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-list',
  'color' => '#000000',
  'parent_id' => 17,
  'order' => 3,
  'created_at' => '2024-10-17 15:53:37',
  'updated_at' => '2024-12-10 15:21:28',
  'route' => 'voyager.corporate-client.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 30,
  'menu_id' => 1,
  'title' => 'Overview',
  'url' => 'admin/product-redemption',
  'target' => '_self',
  'icon_class' => 'voyager-window-list',
  'color' => '#000000',
  'parent_id' => 65,
  'order' => 1,
  'created_at' => '2024-12-06 13:48:40',
  'updated_at' => '2025-03-20 05:35:12',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 31,
  'menu_id' => 1,
  'title' => 'Agency Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-folder',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 3,
  'created_at' => '2024-12-10 09:57:59',
  'updated_at' => '2024-12-10 10:00:16',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 32,
  'menu_id' => 1,
  'title' => 'Downline Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-double-down',
  'color' => '#000000',
  'parent_id' => 31,
  'order' => 2,
  'created_at' => '2024-12-10 09:59:26',
  'updated_at' => '2024-12-10 09:59:36',
  'route' => 'agent.downline',
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 34,
  'menu_id' => 1,
  'title' => 'Profit Sharing Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-bar-chart',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 7,
  'created_at' => '2024-12-17 11:38:56',
  'updated_at' => '2025-08-19 13:35:01',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 35,
  'menu_id' => 1,
  'title' => 'Overview',
  'url' => '/admin/dividend-history',
  'target' => '_self',
  'icon_class' => 'voyager-window-list',
  'color' => '#000000',
  'parent_id' => 34,
  'order' => 1,
  'created_at' => '2024-12-17 11:41:59',
  'updated_at' => '2025-02-21 10:06:28',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 36,
  'menu_id' => 1,
  'title' => 'Checker',
  'url' => '/admin/dividend_checker/',
  'target' => '_self',
  'icon_class' => 'voyager-check-circle',
  'color' => '#000000',
  'parent_id' => 34,
  'order' => 2,
  'created_at' => '2024-12-17 11:43:02',
  'updated_at' => '2025-03-19 18:13:40',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 37,
  'menu_id' => 1,
  'title' => 'Approver',
  'url' => '/admin/dividend_approval',
  'target' => '_self',
  'icon_class' => 'voyager-star',
  'color' => '#000000',
  'parent_id' => 34,
  'order' => 3,
  'created_at' => '2024-12-17 11:43:26',
  'updated_at' => '2025-03-19 18:13:40',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 38,
  'menu_id' => 1,
  'title' => 'Overview',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-window-list',
  'color' => '#000000',
  'parent_id' => 39,
  'order' => 5,
  'created_at' => '2024-12-17 14:08:24',
  'updated_at' => '2025-04-15 15:30:56',
  'route' => 'voyager.product-commission-history.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 39,
  'menu_id' => 1,
  'title' => 'Commission Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-credit-cards',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 8,
  'created_at' => '2024-12-17 14:09:06',
  'updated_at' => '2025-04-08 10:01:12',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 40,
  'menu_id' => 1,
  'title' => 'Checker',
  'url' => '/admin/commission_checker',
  'target' => '_self',
  'icon_class' => 'voyager-check',
  'color' => '#000000',
  'parent_id' => 39,
  'order' => 6,
  'created_at' => '2024-12-17 14:26:51',
  'updated_at' => '2025-04-15 15:30:56',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 41,
  'menu_id' => 1,
  'title' => 'Approver',
  'url' => '/admin/commission_approval',
  'target' => '_self',
  'icon_class' => 'voyager-star',
  'color' => '#000000',
  'parent_id' => 39,
  'order' => 7,
  'created_at' => '2024-12-17 14:27:58',
  'updated_at' => '2025-04-15 15:30:56',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 42,
  'menu_id' => 1,
  'title' => 'Product Order Finance',
  'url' => '/admin/product-order-finance',
  'target' => '_self',
  'icon_class' => 'voyager-window-list',
  'color' => '#000000',
  'parent_id' => 49,
  'order' => 2,
  'created_at' => '2024-12-18 17:48:38',
  'updated_at' => '2025-04-02 09:17:26',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 43,
  'menu_id' => 1,
  'title' => 'Product Order Checker',
  'url' => '/admin/product-order-checker',
  'target' => '_self',
  'icon_class' => 'voyager-check-circle',
  'color' => '#000000',
  'parent_id' => 49,
  'order' => 1,
  'created_at' => '2024-12-18 17:49:14',
  'updated_at' => '2025-04-02 09:17:26',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 44,
  'menu_id' => 1,
  'title' => 'Product Order Approver',
  'url' => '/admin/product-order-approver',
  'target' => '_self',
  'icon_class' => 'voyager-star',
  'color' => '#000000',
  'parent_id' => 49,
  'order' => 3,
  'created_at' => '2024-12-18 17:49:51',
  'updated_at' => '2025-03-19 18:13:36',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 46,
  'menu_id' => 1,
  'title' => 'Product Agreement Schedules',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-calendar',
  'color' => '#000000',
  'parent_id' => 47,
  'order' => 3,
  'created_at' => '2024-12-27 16:11:35',
  'updated_at' => '2024-12-27 16:21:20',
  'route' => 'voyager.product-agreement-schedule.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 47,
  'menu_id' => 1,
  'title' => 'Agreement Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-logbook',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 4,
  'created_at' => '2024-12-27 16:12:48',
  'updated_at' => '2025-03-18 16:15:18',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 49,
  'menu_id' => 1,
  'title' => 'Fund Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-archive',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 6,
  'created_at' => '2024-12-30 22:09:36',
  'updated_at' => '2025-04-08 10:00:39',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 50,
  'menu_id' => 1,
  'title' => 'Product Profit Sharing Schedules',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-list',
  'color' => '#000000',
  'parent_id' => 27,
  'order' => 4,
  'created_at' => '2024-12-30 23:40:00',
  'updated_at' => '2025-08-25 16:51:33',
  'route' => 'voyager.product-dividend-schedule.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 51,
  'menu_id' => 1,
  'title' => 'Maintenance Windows',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-warning',
  'color' => '#000000',
  'parent_id' => 5,
  'order' => 1,
  'created_at' => '2025-01-08 11:33:58',
  'updated_at' => '2025-03-05 21:31:46',
  'route' => 'voyager.maintenance-window.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 54,
  'menu_id' => 1,
  'title' => 'Agency Commission Configurations',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-shop',
  'color' => '#000000',
  'parent_id' => 39,
  'order' => 1,
  'created_at' => '2025-01-16 16:12:12',
  'updated_at' => '2025-03-18 16:15:18',
  'route' => 'voyager.agency-commission-configuration.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 55,
  'menu_id' => 1,
  'title' => 'Early Redemption Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-credit-card',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 9,
  'created_at' => '2025-01-27 10:12:13',
  'updated_at' => '2025-04-11 17:17:01',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 57,
  'menu_id' => 1,
  'title' => 'Checker',
  'url' => '/admin/withdrawal-checker',
  'target' => '_self',
  'icon_class' => 'voyager-check-circle',
  'color' => '#000000',
  'parent_id' => 55,
  'order' => 2,
  'created_at' => '2025-01-27 10:17:19',
  'updated_at' => '2025-03-20 05:34:56',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 58,
  'menu_id' => 1,
  'title' => 'Approver',
  'url' => '/admin/withdrawal-approver',
  'target' => '_self',
  'icon_class' => 'voyager-star',
  'color' => '#000000',
  'parent_id' => 55,
  'order' => 3,
  'created_at' => '2025-01-27 10:17:24',
  'updated_at' => '2025-03-19 18:13:46',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 59,
  'menu_id' => 1,
  'title' => 'In-House Commission Configurations',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-shop',
  'color' => '#000000',
  'parent_id' => 39,
  'order' => 4,
  'created_at' => '2025-02-12 18:41:52',
  'updated_at' => '2025-04-15 15:30:56',
  'route' => 'voyager.agent-commission-configuration.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 61,
  'menu_id' => 1,
  'title' => 'Product Agreement Dates',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-calendar',
  'color' => '#000000',
  'parent_id' => 27,
  'order' => 5,
  'created_at' => '2025-02-13 20:03:12',
  'updated_at' => '2025-03-19 18:13:33',
  'route' => 'voyager.product-agreement-date.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 62,
  'menu_id' => 1,
  'title' => 'Report',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-documentation',
  'color' => '#000000',
  'parent_id' => 34,
  'order' => 4,
  'created_at' => '2025-02-21 19:25:12',
  'updated_at' => '2025-03-19 18:13:40',
  'route' => 'dividend-report.index',
  'parameters' => 'null',
));
        DB::table('menu_items')->insert(array (
  'id' => 63,
  'menu_id' => 1,
  'title' => 'Media',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-images',
  'color' => NULL,
  'parent_id' => 5,
  'order' => 3,
  'created_at' => '2025-02-23 02:02:53',
  'updated_at' => '2025-04-08 10:01:21',
  'route' => 'voyager.media.index',
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 64,
  'menu_id' => 1,
  'title' => 'Users',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-person',
  'color' => NULL,
  'parent_id' => 16,
  'order' => 2,
  'created_at' => '2025-02-23 02:02:53',
  'updated_at' => '2025-03-18 16:16:52',
  'route' => 'voyager.users.index',
  'parameters' => NULL,
));
        DB::table('menu_items')->insert(array (
  'id' => 65,
  'menu_id' => 1,
  'title' => 'Redemption Management',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-file-text',
  'color' => '#000000',
  'parent_id' => NULL,
  'order' => 10,
  'created_at' => '2025-02-25 09:19:22',
  'updated_at' => '2025-04-08 10:01:12',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 66,
  'menu_id' => 1,
  'title' => 'Redemption Checker',
  'url' => 'admin/redemption-checker',
  'target' => '_self',
  'icon_class' => 'voyager-check',
  'color' => '#000000',
  'parent_id' => 65,
  'order' => 2,
  'created_at' => '2025-02-25 09:20:02',
  'updated_at' => '2025-03-19 18:13:46',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 67,
  'menu_id' => 1,
  'title' => 'Redemption Approver',
  'url' => 'admin/redemption-approver',
  'target' => '_self',
  'icon_class' => 'voyager-star',
  'color' => '#000000',
  'parent_id' => 65,
  'order' => 3,
  'created_at' => '2025-02-25 09:20:42',
  'updated_at' => '2025-03-19 18:13:46',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 70,
  'menu_id' => 1,
  'title' => 'Product Reallocation Checker',
  'url' => 'admin/product-reallocation-checker',
  'target' => '_self',
  'icon_class' => 'voyager-check',
  'color' => '#000000',
  'parent_id' => 69,
  'order' => 1,
  'created_at' => '2025-02-27 15:36:13',
  'updated_at' => '2025-03-11 11:26:47',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 71,
  'menu_id' => 1,
  'title' => 'Product Reallocation Approver',
  'url' => 'admin/product-reallocation-approver',
  'target' => '_self',
  'icon_class' => 'voyager-star',
  'color' => '#000000',
  'parent_id' => 69,
  'order' => 2,
  'created_at' => '2025-02-27 15:36:15',
  'updated_at' => '2025-03-11 11:26:47',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 73,
  'menu_id' => 1,
  'title' => 'Product Rollover Checker',
  'url' => 'admin/product-rollover-history-checker',
  'target' => '_self',
  'icon_class' => 'voyager-check',
  'color' => '#000000',
  'parent_id' => 72,
  'order' => 1,
  'created_at' => '2025-02-27 15:37:51',
  'updated_at' => '2025-03-11 16:23:17',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 74,
  'menu_id' => 1,
  'title' => 'Product Rollover Approver',
  'url' => 'admin/product-rollover-history-approver',
  'target' => '_self',
  'icon_class' => 'voyager-star',
  'color' => '#000000',
  'parent_id' => 72,
  'order' => 2,
  'created_at' => '2025-02-27 15:38:12',
  'updated_at' => '2025-03-11 16:23:17',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 75,
  'menu_id' => 1,
  'title' => 'Agent Commission Dashboard',
  'url' => '/admin/agent-commission-dashboard',
  'target' => '_self',
  'icon_class' => 'voyager-dashboard',
  'color' => '#000000',
  'parent_id' => 39,
  'order' => 3,
  'created_at' => '2025-03-11 16:23:11',
  'updated_at' => '2025-04-15 15:30:56',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 76,
  'menu_id' => 1,
  'title' => 'Overview',
  'url' => '/admin/product-early-redemption-history',
  'target' => '_self',
  'icon_class' => 'voyager-window-list',
  'color' => '#000000',
  'parent_id' => 55,
  'order' => 1,
  'created_at' => '2025-03-15 23:08:58',
  'updated_at' => '2025-03-20 05:34:56',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 77,
  'menu_id' => 1,
  'title' => 'Agency Commission Dashboard',
  'url' => 'admin/agency-commission-dashboard',
  'target' => '_self',
  'icon_class' => 'voyager-puzzle',
  'color' => '#000000',
  'parent_id' => 39,
  'order' => 2,
  'created_at' => '2025-04-15 15:29:42',
  'updated_at' => '2025-04-15 15:30:56',
  'route' => NULL,
  'parameters' => '',
));
        DB::table('menu_items')->insert(array (
  'id' => 79,
  'menu_id' => 1,
  'title' => 'App Users',
  'url' => '',
  'target' => '_self',
  'icon_class' => 'voyager-mail',
  'color' => NULL,
  'parent_id' => NULL,
  'order' => 15,
  'created_at' => '2025-08-15 14:31:07',
  'updated_at' => '2025-08-15 14:31:07',
  'route' => 'voyager.app-users.index',
  'parameters' => NULL,
));
    }
}
