#SPRING
spring.datasource.url=jdbc:mysql://localhost:3306/citadel?serverTimezone=Asia/Kuala_Lumpur
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=false

#PROJECT#
server.env=Staging
project.url=https://api.citadel.nexstream.com.my/citadelBackend
file.storage.location=/home/appxtream/citadel/filesUpload
citadel.cms.host=https://admin.citadel.nexstream.com.my/admin

#FaceNet Sidecar Service
facenet.sidecar.url=http://localhost:3001

#EMAIL SERVICE SENDGRID
sendgrid.api-key=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
sendgrid.from-email=post.service@citadelgroup.com.my

citadel.second.signee.webpage.link=https://api.citadel.nexstream.com.my/agreement/#/?env=dev&data=